from .login_form import LoginForm
from .signup_form import SignUpForm
from .new_dog import NewDogForm
from .new_walk import NewWalk
from .update_walk import UpdatedWalk
from .new_review import NewReview
from .update_review import UpdateReview
from .search_form import SearchForm
from .update_user_name import UpdateName
from .update_user_email import UpdateEmail
from .update_user_pic import UpdatePicture
from .update_password import UpdatePassword
