"""empty message

Revision ID: a0c4dbf71abd
Revises: b39116d6c58c
Create Date: 2021-11-21 09:12:59.853000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c4dbf71abd'
down_revision = 'b39116d6c58c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'images', ['id'])
    op.add_column('reviews', sa.Column('avgRating', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'avgRating')
    op.drop_constraint(None, 'images', type_='unique')
    # ### end Alembic commands ###
